# -*- coding: utf-8 -*-
"""Streamlit App

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fgtGtXwcjk7XfiEwB1cmkun1wcXLc-IG
"""

import streamlit as st
import joblib
from keras.models import load_model
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# Load TF-IDF vectorizer and Keras model
vectorizer = joblib.load('C:\\Users\\DELL\\AppData\\Local\\Temp\\tfidf_vectorizer.joblib')
model = load_model('C:\\Users\\DELL\\Documents\\sentiment_analysis_model.h5')



# Function to predict sentiment
def predict_sentiment(text):
    text_tfidf = vectorizer.transform([text])
    text_tfidf_dense = text_tfidf.toarray()  # Convert sparse matrix to dense NumPy array
    text_tfidf_reshaped = np.expand_dims(text_tfidf_dense, axis=1)  # Add extra dimension
    prediction = model.predict(text_tfidf_reshaped)
    return np.argmax(prediction)


# Streamlit app
st.title('Sentiment Analysis App')

user_input = st.text_input('Enter text:', '')

if st.button('Predict Sentiment'):
    if user_input.strip() != '':
        sentiment_label = predict_sentiment(user_input)
        if sentiment_label == 1:
            st.write('Predicted sentiment: Positive')
        else:
            st.write('Predicted sentiment: Negative')
    else:
        st.write('Please enter some text.')


